# example atune config
[[project]]
on_sync = ["echo some sync done"]
[[project.sync]]
src = "/tmp/atune/"
dst = "fragilis:~/atune/foo"
rsync_flags = "-urltv --delete --progress"

[[project]]
[[project.sync]]
src = "/tmp/atune/bar"
dst = "fragilis:~/atune/bar"
on_sync = [
    "echo foo",
    "echo bar",
    "echo baz",
    "ssh fragilis -C 'echo done > ~/atune/test.txt'",
]
